version: '3.9'

x-app-setup: &app-setup
  image: 'customer-app:latest'
  env_file:
    - '.env.local'
  depends_on:
    database:
      condition: service_healthy
  volumes:
    - ./src:/app

services:

  app:
    <<: *app-setup
    ports:
      - '${DOCKER_APPLICATION_EXPOSE_PORT}:${WEB_APPLICATION_PORT}'
    entrypoint: [
      "uvicorn", "app.interface.web.app:web_app",
      "--host", "0.0.0.0",
      "--port", "${WEB_APPLICATION_PORT}",
      "--debug",
    ]

  app-migration:
    <<: *app-setup

  database:
    image: 'postgres:latest'
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    ports:
      - '${DOCKER_DATABASE_EXPOSE_PORT}:5432'
    volumes:
      - customer_app_db:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}" ]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  customer_app_db: